version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: nginx_auth_request_api
    build:
      context: .
      dockerfile: Api/Dockerfile
    networks:
      - nginx-auth-request

  authenticationserver:
    image: ${DOCKER_REGISTRY-}authenticationserver
    container_name: nginx_auth_request_authenticationserver
    build:
      context: .
      dockerfile: AuthenticationServer/Dockerfile
    networks:
      - nginx-auth-request

  nginx:
    container_name: nginx_auth_request_nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-auth-request

networks:
  nginx-auth-request: